sonar.projectKey=messinisk_software_architecture_model_js
sonar.organization=messinisk

sonar.sources=src
sonar.tests=tests

sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8

# Αν αργότερα βάλεις coverage:
sonar.javascript.lcov.reportPaths=coverage/lcov.info
