[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "software_architecture_model_python"
version = "1.0.0"
description = "Software architecture models ( DDD, Event‑Driven, Flow_Based_Architecture, MVC, MVVM) in Python."
authors = [
    { name = "Κώστας" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "networkx",
    "deepdiff",
    "typer",
    "jsonschema"

] # Προσθέστε python εξαρτήσεις αν υπάρχουν


[tool.ruff]
line-length = 100
target-version = "py311"
lint.select = ["E", "F", "W", "I", "B", "UP"]
lint.ignore = ["E501"]
exclude = ["venv", "build", "dist"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
strict = false
exclude = ["venv"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = [
    "tests"
]

[tool.setuptools.packages.find]
where = ["src"]