name: Docker Python

on:
  push:
    branches:
      - python3

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Python image
        run: |
          docker build \
            -f software_architecture_model_python/Dockerfile \
            -t sam-python .