name: Docker JS

on:
  push:
    branches:
      - js-package

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Node image
        run: |
          docker build \
            -f js_package/Dockerfile \
            -t sam-js .