# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow file requires a free account on Semgrep.dev to
# manage rules, file ignores, notifications, and more.
#
# See https://semgrep.dev/docs

name: Semgrep (js_package only)

on:
  push:
    branches: [ "js-package" ]
  pull_request:
    branches: [ "js-package" ]
  schedule:
    - cron: '39 7 * * 4'

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Scan JS Package
    runs-on: ubuntu-latest

    steps:
      # Checkout ONLY js_package folder
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            js_package
          sparse-checkout-cone-mode: false

      # Run Semgrep scan ONLY inside js_package
      - uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"
          config: "p/ts"        # Semgrep official TypeScript rules
          include: "js_package" # restrict scan to js_package

      # Upload SARIF results to GitHub Security
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
