name: SonarCloud analysis

on:
  push:
    branches: [ "js-package" ]
  pull_request:
    branches: [ "js-package" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout js_package only
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            js_package
          sparse-checkout-cone-mode: false

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: js_package
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: js_package
          args: >
            -Dsonar.projectKey=messinisk_software_architecture_model_js
            -Dsonar.organization=messinisk
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.typescript.tsconfigPath=tsconfig.json
